// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Entity;

public partial class Course
{
    public int CourseId { get; set; }

    public string CourseName { get; set; }

    public string Description { get; set; }

    public string Type { get; set; }

    public decimal Price { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
    public DateTime? DeleteAt { get; set; }

    public virtual ICollection<Class> Classes { get; set; } = new List<Class>();

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<Resource> Resources { get; set; } = new List<Resource>();
}