// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Entity;

public partial class NewsEvent
{
    public int NewsId { get; set; }
    [Column(TypeName = "nvarchar(255)")]
    public string Title { get; set; }
    [Column(TypeName = "nvarchar(max)")]
    public string Content { get; set; }

    public string Category { get; set; }

    public DateTime? EventDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
    public DateTime? DeleteAt { get; set; }

    public virtual User CreatedByNavigation { get; set; }
}