// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Entity;

public partial class Project
{
    public int ProjectId { get; set; }
    [Column(TypeName = "nvarchar(255)")]
    public string ProjectName { get; set; }
    [Column(TypeName = "nvarchar(max)")]
    public string Description { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    [Column(TypeName = "varchar(20)")]
    public string Status { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
    public DateTime? DeleteAt { get; set; }

    public virtual User CreatedByNavigation { get; set; }
}