// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Entity;

public partial class Resource
{
    public int ResourceId { get; set; }

    public int CourseId { get; set; }

    public string ResourceName { get; set; }

    public string ResourceType { get; set; }

    public string FileUrl { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
    public DateTime? DeleteAt { get; set; }

    public virtual Course Course { get; set; }

    public virtual User CreatedByNavigation { get; set; }
}